### ISSUE TITLE
Ne fonctionne pas sur Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [ukinoki/Rufus#11]
Les ingrédients utilisés dans votre AppImage ne doivent pas être construits sur un système de base plus récent que le système de base le plus ancien sur lequel votre AppImage est destiné à fonctionner. Certaines librairies centrales, comme la glibc, ont tendance à rompre assez fréquemment la compatibilité avec les systèmes de base plus anciens, ce qui signifie que les binaires fonctionneront sur des systèmes de base plus récents, mais pas sur des systèmes de base plus anciens que celui sur lequel les binaires ont été compilés.

Puisque nous sommes confrontés à des erreurs telles que

`AppRun: /usr/lib/x86_64-linux-gnu/libstdc+++.so.6 : version 'CXXABI_1.3.9' introuvable (requis par /run/firejail/appimage/.appimage-9912/lib/libQt5PrintSupport.so.5)`

le binaire est compilé sur un système plus récent que celui sur lequel nous essayons de l'exécuter. Veuillez utiliser des binaires qui ont été compilés sur un système plus ancien. 

Veuillez donc compiler sur Ubuntu 14.04, qui est actuellement la plus ancienne version d'Ubuntu encore supportée. Si vous le construisez sur Ubuntu 14.04, alors il devrait fonctionner sur la plupart des distributions à partir de 2014 et plus récentes.

https://github.com/AppImage/appimage.github.io/pull/682

**Comment by ukinoki** [comment]
Hi, thanks for the comment, i'll try to switch to trusty. First choice of xenial was for the availibity of poppler's libs... 
An other concern is the integration of the mysql qt driver in appimage even with the extra plugin option, it doesn't work all the time, is it a common issue ?

**Comment by probonopd** [comment]
Yes, a switch to trusty would be great. Possibly it also solves the deployment of the mysql qt driver using `-extra-plugins=sqldrivers`.

**Comment by ukinoki** [comment]
Done :)

**Comment by probonopd** [comment]
Thank you very much. Now it is _almost_ working, giving this upon first launch:

![](https://github.com/AppImage/appimage.github.io/blob/56ec2bc003207845c6cbf3fa9ba551c8976f21df/database/Rufus/screenshot.png?raw=true)

Is this normal?

**Comment by ukinoki** [comment]
This is normal, at the first start, the rufus.ini file will be created once the link with the mysql database is done

**Comment by probonopd** [comment]
OK, great. It's working then. Thank you very much!
